#BOo weeb program 
EIGHTEEN_YEARS_OLD_OLDER_PRICE = 12
TWELVE_YEARS_OLD_OLDER_PRICE = 9
FIVE_YEARS_OLD_OLDER_PRICE = 7
STUDENT_OVER_EIGHTEEN_PRICE = 8
EIGHTEEN_PRICE_THRESHOLD = 18
THIRTEEN_PRICE_THRESHOLD = 9
FIVE_PRICE_THRESHOLD = 5

age = int(input("How old are you"))

If age >= THIRTEEN_PRICE_THRESHOLD and 